// tslint:disable
/**
 * 健康助手后台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { DiseaseRecordVo } from '../models';
// @ts-ignore
import { FormResult } from '../models';
// @ts-ignore
import { Result } from '../models';
/**
 * DiseaseRecordControllerApi - axios parameter creator
 * @export
 */
export const DiseaseRecordControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 根据id批量删除疾病记录表
         * @summary 根据id批量删除疾病记录表
         * @param {Array<string>} diseaseRecordIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        diseaseRecordDelete: async (diseaseRecordIds: Array<string>, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'diseaseRecordIds' is not null or undefined
            if (diseaseRecordIds === null || diseaseRecordIds === undefined) {
                throw new RequiredError('diseaseRecordIds','Required parameter diseaseRecordIds was null or undefined when calling diseaseRecordDelete.');
            }
            const localVarPath = `/DiseaseRecord/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (diseaseRecordIds) {
                localVarQueryParameter['diseaseRecordIds'] = diseaseRecordIds;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 分页查询所有疾病记录
         * @summary 分页查询所有疾病记录
         * @param {number} page 
         * @param {number} num 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        diseaseRecordGet: async (page: number, num: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            if (page === null || page === undefined) {
                throw new RequiredError('page','Required parameter page was null or undefined when calling diseaseRecordGet.');
            }
            // verify required parameter 'num' is not null or undefined
            if (num === null || num === undefined) {
                throw new RequiredError('num','Required parameter num was null or undefined when calling diseaseRecordGet.');
            }
            const localVarPath = `/DiseaseRecord/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (num !== undefined) {
                localVarQueryParameter['num'] = num;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 根据用户名称模糊分页查询所有疾病记录表
         * @summary 根据用户名称模糊分页查询所有疾病记录表
         * @param {string} page 
         * @param {string} num 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        diseaseRecordPageNumGet: async (page: string, num: string, name: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            if (page === null || page === undefined) {
                throw new RequiredError('page','Required parameter page was null or undefined when calling diseaseRecordPageNumGet.');
            }
            // verify required parameter 'num' is not null or undefined
            if (num === null || num === undefined) {
                throw new RequiredError('num','Required parameter num was null or undefined when calling diseaseRecordPageNumGet.');
            }
            // verify required parameter 'name' is not null or undefined
            if (name === null || name === undefined) {
                throw new RequiredError('name','Required parameter name was null or undefined when calling diseaseRecordPageNumGet.');
            }
            const localVarPath = `/DiseaseRecord/{page}/{num}`
                .replace(`{${"page"}}`, encodeURIComponent(String(page)))
                .replace(`{${"num"}}`, encodeURIComponent(String(num)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 增加疾病记录表(id需要为null，有病是1，没病是0)
         * @summary 增加疾病记录表(id需要为null)
         * @param {DiseaseRecordVo} [diseaseRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        diseaseRecordPost: async (diseaseRecordVo?: DiseaseRecordVo, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/DiseaseRecord/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof diseaseRecordVo !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(diseaseRecordVo !== undefined ? diseaseRecordVo : {}) : (diseaseRecordVo || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 修改疾病记录表
         * @summary 修改疾病记录表
         * @param {DiseaseRecordVo} [diseaseRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        diseaseRecordPut: async (diseaseRecordVo?: DiseaseRecordVo, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/DiseaseRecord/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof diseaseRecordVo !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(diseaseRecordVo !== undefined ? diseaseRecordVo : {}) : (diseaseRecordVo || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DiseaseRecordControllerApi - functional programming interface
 * @export
 */
export const DiseaseRecordControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 根据id批量删除疾病记录表
         * @summary 根据id批量删除疾病记录表
         * @param {Array<string>} diseaseRecordIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async diseaseRecordDelete(diseaseRecordIds: Array<string>, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Result>> {
            const localVarAxiosArgs = await DiseaseRecordControllerApiAxiosParamCreator(configuration).diseaseRecordDelete(diseaseRecordIds, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 分页查询所有疾病记录
         * @summary 分页查询所有疾病记录
         * @param {number} page 
         * @param {number} num 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async diseaseRecordGet(page: number, num: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormResult>> {
            const localVarAxiosArgs = await DiseaseRecordControllerApiAxiosParamCreator(configuration).diseaseRecordGet(page, num, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 根据用户名称模糊分页查询所有疾病记录表
         * @summary 根据用户名称模糊分页查询所有疾病记录表
         * @param {string} page 
         * @param {string} num 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async diseaseRecordPageNumGet(page: string, num: string, name: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormResult>> {
            const localVarAxiosArgs = await DiseaseRecordControllerApiAxiosParamCreator(configuration).diseaseRecordPageNumGet(page, num, name, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 增加疾病记录表(id需要为null，有病是1，没病是0)
         * @summary 增加疾病记录表(id需要为null)
         * @param {DiseaseRecordVo} [diseaseRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async diseaseRecordPost(diseaseRecordVo?: DiseaseRecordVo, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Result>> {
            const localVarAxiosArgs = await DiseaseRecordControllerApiAxiosParamCreator(configuration).diseaseRecordPost(diseaseRecordVo, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 修改疾病记录表
         * @summary 修改疾病记录表
         * @param {DiseaseRecordVo} [diseaseRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async diseaseRecordPut(diseaseRecordVo?: DiseaseRecordVo, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Result>> {
            const localVarAxiosArgs = await DiseaseRecordControllerApiAxiosParamCreator(configuration).diseaseRecordPut(diseaseRecordVo, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DiseaseRecordControllerApi - factory interface
 * @export
 */
export const DiseaseRecordControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 根据id批量删除疾病记录表
         * @summary 根据id批量删除疾病记录表
         * @param {Array<string>} diseaseRecordIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        diseaseRecordDelete(diseaseRecordIds: Array<string>, options?: any): AxiosPromise<Result> {
            return DiseaseRecordControllerApiFp(configuration).diseaseRecordDelete(diseaseRecordIds, options).then((request) => request(axios, basePath));
        },
        /**
         * 分页查询所有疾病记录
         * @summary 分页查询所有疾病记录
         * @param {number} page 
         * @param {number} num 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        diseaseRecordGet(page: number, num: number, options?: any): AxiosPromise<FormResult> {
            return DiseaseRecordControllerApiFp(configuration).diseaseRecordGet(page, num, options).then((request) => request(axios, basePath));
        },
        /**
         * 根据用户名称模糊分页查询所有疾病记录表
         * @summary 根据用户名称模糊分页查询所有疾病记录表
         * @param {string} page 
         * @param {string} num 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        diseaseRecordPageNumGet(page: string, num: string, name: string, options?: any): AxiosPromise<FormResult> {
            return DiseaseRecordControllerApiFp(configuration).diseaseRecordPageNumGet(page, num, name, options).then((request) => request(axios, basePath));
        },
        /**
         * 增加疾病记录表(id需要为null，有病是1，没病是0)
         * @summary 增加疾病记录表(id需要为null)
         * @param {DiseaseRecordVo} [diseaseRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        diseaseRecordPost(diseaseRecordVo?: DiseaseRecordVo, options?: any): AxiosPromise<Result> {
            return DiseaseRecordControllerApiFp(configuration).diseaseRecordPost(diseaseRecordVo, options).then((request) => request(axios, basePath));
        },
        /**
         * 修改疾病记录表
         * @summary 修改疾病记录表
         * @param {DiseaseRecordVo} [diseaseRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        diseaseRecordPut(diseaseRecordVo?: DiseaseRecordVo, options?: any): AxiosPromise<Result> {
            return DiseaseRecordControllerApiFp(configuration).diseaseRecordPut(diseaseRecordVo, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DiseaseRecordControllerApi - object-oriented interface
 * @export
 * @class DiseaseRecordControllerApi
 * @extends {BaseAPI}
 */
export class DiseaseRecordControllerApi extends BaseAPI {
    /**
     * 根据id批量删除疾病记录表
     * @summary 根据id批量删除疾病记录表
     * @param {Array<string>} diseaseRecordIds 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiseaseRecordControllerApi
     */
    public diseaseRecordDelete(diseaseRecordIds: Array<string>, options?: any) {
        return DiseaseRecordControllerApiFp(this.configuration).diseaseRecordDelete(diseaseRecordIds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 分页查询所有疾病记录
     * @summary 分页查询所有疾病记录
     * @param {number} page 
     * @param {number} num 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiseaseRecordControllerApi
     */
    public diseaseRecordGet(page: number, num: number, options?: any) {
        return DiseaseRecordControllerApiFp(this.configuration).diseaseRecordGet(page, num, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 根据用户名称模糊分页查询所有疾病记录表
     * @summary 根据用户名称模糊分页查询所有疾病记录表
     * @param {string} page 
     * @param {string} num 
     * @param {string} name 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiseaseRecordControllerApi
     */
    public diseaseRecordPageNumGet(page: string, num: string, name: string, options?: any) {
        return DiseaseRecordControllerApiFp(this.configuration).diseaseRecordPageNumGet(page, num, name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 增加疾病记录表(id需要为null，有病是1，没病是0)
     * @summary 增加疾病记录表(id需要为null)
     * @param {DiseaseRecordVo} [diseaseRecordVo] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiseaseRecordControllerApi
     */
    public diseaseRecordPost(diseaseRecordVo?: DiseaseRecordVo, options?: any) {
        return DiseaseRecordControllerApiFp(this.configuration).diseaseRecordPost(diseaseRecordVo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 修改疾病记录表
     * @summary 修改疾病记录表
     * @param {DiseaseRecordVo} [diseaseRecordVo] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DiseaseRecordControllerApi
     */
    public diseaseRecordPut(diseaseRecordVo?: DiseaseRecordVo, options?: any) {
        return DiseaseRecordControllerApiFp(this.configuration).diseaseRecordPut(diseaseRecordVo, options).then((request) => request(this.axios, this.basePath));
    }

}
