// tslint:disable
/**
 * 健康助手后台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { FoodMapping } from '../models';
// @ts-ignore
import { FormResult } from '../models';
// @ts-ignore
import { Result } from '../models';
/**
 * FoodMappingControllerApi - axios parameter creator
 * @export
 */
export const FoodMappingControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 根据id批量删除图片识别映射
         * @summary 根据id批量删除图片识别映射
         * @param {Array<string>} foodMappingIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        foodMappingDelete: async (foodMappingIds: Array<string>, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'foodMappingIds' is not null or undefined
            if (foodMappingIds === null || foodMappingIds === undefined) {
                throw new RequiredError('foodMappingIds','Required parameter foodMappingIds was null or undefined when calling foodMappingDelete.');
            }
            const localVarPath = `/foodMapping`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (foodMappingIds) {
                localVarQueryParameter['FoodMappingIds'] = foodMappingIds;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 分页查询所有图片识别映射
         * @summary 分页查询所有图片识别映射
         * @param {number} page 
         * @param {number} num 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        foodMappingGet: async (page: number, num: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            if (page === null || page === undefined) {
                throw new RequiredError('page','Required parameter page was null or undefined when calling foodMappingGet.');
            }
            // verify required parameter 'num' is not null or undefined
            if (num === null || num === undefined) {
                throw new RequiredError('num','Required parameter num was null or undefined when calling foodMappingGet.');
            }
            const localVarPath = `/foodMapping/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (num !== undefined) {
                localVarQueryParameter['num'] = num;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 根据食物名称模糊分页查询所有图片识别映射
         * @summary 根据食物名称模糊分页查询所有图片识别映射
         * @param {string} page 
         * @param {string} num 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        foodMappingPageNumGet: async (page: string, num: string, name: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            if (page === null || page === undefined) {
                throw new RequiredError('page','Required parameter page was null or undefined when calling foodMappingPageNumGet.');
            }
            // verify required parameter 'num' is not null or undefined
            if (num === null || num === undefined) {
                throw new RequiredError('num','Required parameter num was null or undefined when calling foodMappingPageNumGet.');
            }
            // verify required parameter 'name' is not null or undefined
            if (name === null || name === undefined) {
                throw new RequiredError('name','Required parameter name was null or undefined when calling foodMappingPageNumGet.');
            }
            const localVarPath = `/foodMapping/{page}/{num}`
                .replace(`{${"page"}}`, encodeURIComponent(String(page)))
                .replace(`{${"num"}}`, encodeURIComponent(String(num)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 增加图片识别映射(id需要为null)
         * @summary 增加图片识别映射(id需要为null)
         * @param {FoodMapping} [foodMapping] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        foodMappingPost: async (foodMapping?: FoodMapping, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/foodMapping/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof foodMapping !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(foodMapping !== undefined ? foodMapping : {}) : (foodMapping || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 修改图片识别映射
         * @summary 修改图片识别映射
         * @param {FoodMapping} [foodMapping] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        foodMappingPut: async (foodMapping?: FoodMapping, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/foodMapping/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof foodMapping !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(foodMapping !== undefined ? foodMapping : {}) : (foodMapping || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FoodMappingControllerApi - functional programming interface
 * @export
 */
export const FoodMappingControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 根据id批量删除图片识别映射
         * @summary 根据id批量删除图片识别映射
         * @param {Array<string>} foodMappingIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async foodMappingDelete(foodMappingIds: Array<string>, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Result>> {
            const localVarAxiosArgs = await FoodMappingControllerApiAxiosParamCreator(configuration).foodMappingDelete(foodMappingIds, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 分页查询所有图片识别映射
         * @summary 分页查询所有图片识别映射
         * @param {number} page 
         * @param {number} num 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async foodMappingGet(page: number, num: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormResult>> {
            const localVarAxiosArgs = await FoodMappingControllerApiAxiosParamCreator(configuration).foodMappingGet(page, num, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 根据食物名称模糊分页查询所有图片识别映射
         * @summary 根据食物名称模糊分页查询所有图片识别映射
         * @param {string} page 
         * @param {string} num 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async foodMappingPageNumGet(page: string, num: string, name: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormResult>> {
            const localVarAxiosArgs = await FoodMappingControllerApiAxiosParamCreator(configuration).foodMappingPageNumGet(page, num, name, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 增加图片识别映射(id需要为null)
         * @summary 增加图片识别映射(id需要为null)
         * @param {FoodMapping} [foodMapping] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async foodMappingPost(foodMapping?: FoodMapping, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Result>> {
            const localVarAxiosArgs = await FoodMappingControllerApiAxiosParamCreator(configuration).foodMappingPost(foodMapping, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 修改图片识别映射
         * @summary 修改图片识别映射
         * @param {FoodMapping} [foodMapping] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async foodMappingPut(foodMapping?: FoodMapping, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Result>> {
            const localVarAxiosArgs = await FoodMappingControllerApiAxiosParamCreator(configuration).foodMappingPut(foodMapping, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * FoodMappingControllerApi - factory interface
 * @export
 */
export const FoodMappingControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 根据id批量删除图片识别映射
         * @summary 根据id批量删除图片识别映射
         * @param {Array<string>} foodMappingIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        foodMappingDelete(foodMappingIds: Array<string>, options?: any): AxiosPromise<Result> {
            return FoodMappingControllerApiFp(configuration).foodMappingDelete(foodMappingIds, options).then((request) => request(axios, basePath));
        },
        /**
         * 分页查询所有图片识别映射
         * @summary 分页查询所有图片识别映射
         * @param {number} page 
         * @param {number} num 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        foodMappingGet(page: number, num: number, options?: any): AxiosPromise<FormResult> {
            return FoodMappingControllerApiFp(configuration).foodMappingGet(page, num, options).then((request) => request(axios, basePath));
        },
        /**
         * 根据食物名称模糊分页查询所有图片识别映射
         * @summary 根据食物名称模糊分页查询所有图片识别映射
         * @param {string} page 
         * @param {string} num 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        foodMappingPageNumGet(page: string, num: string, name: string, options?: any): AxiosPromise<FormResult> {
            return FoodMappingControllerApiFp(configuration).foodMappingPageNumGet(page, num, name, options).then((request) => request(axios, basePath));
        },
        /**
         * 增加图片识别映射(id需要为null)
         * @summary 增加图片识别映射(id需要为null)
         * @param {FoodMapping} [foodMapping] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        foodMappingPost(foodMapping?: FoodMapping, options?: any): AxiosPromise<Result> {
            return FoodMappingControllerApiFp(configuration).foodMappingPost(foodMapping, options).then((request) => request(axios, basePath));
        },
        /**
         * 修改图片识别映射
         * @summary 修改图片识别映射
         * @param {FoodMapping} [foodMapping] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        foodMappingPut(foodMapping?: FoodMapping, options?: any): AxiosPromise<Result> {
            return FoodMappingControllerApiFp(configuration).foodMappingPut(foodMapping, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FoodMappingControllerApi - object-oriented interface
 * @export
 * @class FoodMappingControllerApi
 * @extends {BaseAPI}
 */
export class FoodMappingControllerApi extends BaseAPI {
    /**
     * 根据id批量删除图片识别映射
     * @summary 根据id批量删除图片识别映射
     * @param {Array<string>} foodMappingIds 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FoodMappingControllerApi
     */
    public foodMappingDelete(foodMappingIds: Array<string>, options?: any) {
        return FoodMappingControllerApiFp(this.configuration).foodMappingDelete(foodMappingIds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 分页查询所有图片识别映射
     * @summary 分页查询所有图片识别映射
     * @param {number} page 
     * @param {number} num 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FoodMappingControllerApi
     */
    public foodMappingGet(page: number, num: number, options?: any) {
        return FoodMappingControllerApiFp(this.configuration).foodMappingGet(page, num, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 根据食物名称模糊分页查询所有图片识别映射
     * @summary 根据食物名称模糊分页查询所有图片识别映射
     * @param {string} page 
     * @param {string} num 
     * @param {string} name 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FoodMappingControllerApi
     */
    public foodMappingPageNumGet(page: string, num: string, name: string, options?: any) {
        return FoodMappingControllerApiFp(this.configuration).foodMappingPageNumGet(page, num, name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 增加图片识别映射(id需要为null)
     * @summary 增加图片识别映射(id需要为null)
     * @param {FoodMapping} [foodMapping] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FoodMappingControllerApi
     */
    public foodMappingPost(foodMapping?: FoodMapping, options?: any) {
        return FoodMappingControllerApiFp(this.configuration).foodMappingPost(foodMapping, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 修改图片识别映射
     * @summary 修改图片识别映射
     * @param {FoodMapping} [foodMapping] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FoodMappingControllerApi
     */
    public foodMappingPut(foodMapping?: FoodMapping, options?: any) {
        return FoodMappingControllerApiFp(this.configuration).foodMappingPut(foodMapping, options).then((request) => request(this.axios, this.basePath));
    }

}
