// tslint:disable
/**
 * 健康助手后台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { FormResult } from '../models';
// @ts-ignore
import { Nutrition } from '../models';
// @ts-ignore
import { Result } from '../models';
/**
 * NutritionControllerApi - axios parameter creator
 * @export
 */
export const NutritionControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 根据id批量删除食物营养
         * @summary 根据id批量删除食物营养
         * @param {Array<string>} nutritionIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionDelete: async (nutritionIds: Array<string>, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'nutritionIds' is not null or undefined
            if (nutritionIds === null || nutritionIds === undefined) {
                throw new RequiredError('nutritionIds','Required parameter nutritionIds was null or undefined when calling nutritionDelete.');
            }
            const localVarPath = `/nutrition`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (nutritionIds) {
                localVarQueryParameter['nutritionIds'] = nutritionIds;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 分页查询所有食物营养
         * @summary 分页查询所有食物营养
         * @param {number} page 
         * @param {number} num 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionGet: async (page: number, num: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            if (page === null || page === undefined) {
                throw new RequiredError('page','Required parameter page was null or undefined when calling nutritionGet.');
            }
            // verify required parameter 'num' is not null or undefined
            if (num === null || num === undefined) {
                throw new RequiredError('num','Required parameter num was null or undefined when calling nutritionGet.');
            }
            const localVarPath = `/nutrition/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (num !== undefined) {
                localVarQueryParameter['num'] = num;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 根据食物名称模糊分页查询所有食物营养
         * @summary 根据食物名称模糊分页查询所有食物营养
         * @param {string} page 
         * @param {string} num 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionPageNumGet: async (page: string, num: string, name: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            if (page === null || page === undefined) {
                throw new RequiredError('page','Required parameter page was null or undefined when calling nutritionPageNumGet.');
            }
            // verify required parameter 'num' is not null or undefined
            if (num === null || num === undefined) {
                throw new RequiredError('num','Required parameter num was null or undefined when calling nutritionPageNumGet.');
            }
            // verify required parameter 'name' is not null or undefined
            if (name === null || name === undefined) {
                throw new RequiredError('name','Required parameter name was null or undefined when calling nutritionPageNumGet.');
            }
            const localVarPath = `/nutrition/{page}/{num}`
                .replace(`{${"page"}}`, encodeURIComponent(String(page)))
                .replace(`{${"num"}}`, encodeURIComponent(String(num)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 增加食物营养(id需要为null)
         * @summary 增加食物营养(id需要为null)
         * @param {Nutrition} [nutrition] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionPost: async (nutrition?: Nutrition, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/nutrition/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof nutrition !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(nutrition !== undefined ? nutrition : {}) : (nutrition || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 修改食物营养
         * @summary 修改食物营养
         * @param {Nutrition} [nutrition] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionPut: async (nutrition?: Nutrition, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/nutrition/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof nutrition !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(nutrition !== undefined ? nutrition : {}) : (nutrition || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NutritionControllerApi - functional programming interface
 * @export
 */
export const NutritionControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 根据id批量删除食物营养
         * @summary 根据id批量删除食物营养
         * @param {Array<string>} nutritionIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async nutritionDelete(nutritionIds: Array<string>, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Result>> {
            const localVarAxiosArgs = await NutritionControllerApiAxiosParamCreator(configuration).nutritionDelete(nutritionIds, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 分页查询所有食物营养
         * @summary 分页查询所有食物营养
         * @param {number} page 
         * @param {number} num 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async nutritionGet(page: number, num: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormResult>> {
            const localVarAxiosArgs = await NutritionControllerApiAxiosParamCreator(configuration).nutritionGet(page, num, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 根据食物名称模糊分页查询所有食物营养
         * @summary 根据食物名称模糊分页查询所有食物营养
         * @param {string} page 
         * @param {string} num 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async nutritionPageNumGet(page: string, num: string, name: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormResult>> {
            const localVarAxiosArgs = await NutritionControllerApiAxiosParamCreator(configuration).nutritionPageNumGet(page, num, name, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 增加食物营养(id需要为null)
         * @summary 增加食物营养(id需要为null)
         * @param {Nutrition} [nutrition] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async nutritionPost(nutrition?: Nutrition, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Result>> {
            const localVarAxiosArgs = await NutritionControllerApiAxiosParamCreator(configuration).nutritionPost(nutrition, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 修改食物营养
         * @summary 修改食物营养
         * @param {Nutrition} [nutrition] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async nutritionPut(nutrition?: Nutrition, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Result>> {
            const localVarAxiosArgs = await NutritionControllerApiAxiosParamCreator(configuration).nutritionPut(nutrition, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * NutritionControllerApi - factory interface
 * @export
 */
export const NutritionControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 根据id批量删除食物营养
         * @summary 根据id批量删除食物营养
         * @param {Array<string>} nutritionIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionDelete(nutritionIds: Array<string>, options?: any): AxiosPromise<Result> {
            return NutritionControllerApiFp(configuration).nutritionDelete(nutritionIds, options).then((request) => request(axios, basePath));
        },
        /**
         * 分页查询所有食物营养
         * @summary 分页查询所有食物营养
         * @param {number} page 
         * @param {number} num 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionGet(page: number, num: number, options?: any): AxiosPromise<FormResult> {
            return NutritionControllerApiFp(configuration).nutritionGet(page, num, options).then((request) => request(axios, basePath));
        },
        /**
         * 根据食物名称模糊分页查询所有食物营养
         * @summary 根据食物名称模糊分页查询所有食物营养
         * @param {string} page 
         * @param {string} num 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionPageNumGet(page: string, num: string, name: string, options?: any): AxiosPromise<FormResult> {
            return NutritionControllerApiFp(configuration).nutritionPageNumGet(page, num, name, options).then((request) => request(axios, basePath));
        },
        /**
         * 增加食物营养(id需要为null)
         * @summary 增加食物营养(id需要为null)
         * @param {Nutrition} [nutrition] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionPost(nutrition?: Nutrition, options?: any): AxiosPromise<Result> {
            return NutritionControllerApiFp(configuration).nutritionPost(nutrition, options).then((request) => request(axios, basePath));
        },
        /**
         * 修改食物营养
         * @summary 修改食物营养
         * @param {Nutrition} [nutrition] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionPut(nutrition?: Nutrition, options?: any): AxiosPromise<Result> {
            return NutritionControllerApiFp(configuration).nutritionPut(nutrition, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NutritionControllerApi - object-oriented interface
 * @export
 * @class NutritionControllerApi
 * @extends {BaseAPI}
 */
export class NutritionControllerApi extends BaseAPI {
    /**
     * 根据id批量删除食物营养
     * @summary 根据id批量删除食物营养
     * @param {Array<string>} nutritionIds 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NutritionControllerApi
     */
    public nutritionDelete(nutritionIds: Array<string>, options?: any) {
        return NutritionControllerApiFp(this.configuration).nutritionDelete(nutritionIds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 分页查询所有食物营养
     * @summary 分页查询所有食物营养
     * @param {number} page 
     * @param {number} num 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NutritionControllerApi
     */
    public nutritionGet(page: number, num: number, options?: any) {
        return NutritionControllerApiFp(this.configuration).nutritionGet(page, num, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 根据食物名称模糊分页查询所有食物营养
     * @summary 根据食物名称模糊分页查询所有食物营养
     * @param {string} page 
     * @param {string} num 
     * @param {string} name 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NutritionControllerApi
     */
    public nutritionPageNumGet(page: string, num: string, name: string, options?: any) {
        return NutritionControllerApiFp(this.configuration).nutritionPageNumGet(page, num, name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 增加食物营养(id需要为null)
     * @summary 增加食物营养(id需要为null)
     * @param {Nutrition} [nutrition] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NutritionControllerApi
     */
    public nutritionPost(nutrition?: Nutrition, options?: any) {
        return NutritionControllerApiFp(this.configuration).nutritionPost(nutrition, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 修改食物营养
     * @summary 修改食物营养
     * @param {Nutrition} [nutrition] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NutritionControllerApi
     */
    public nutritionPut(nutrition?: Nutrition, options?: any) {
        return NutritionControllerApiFp(this.configuration).nutritionPut(nutrition, options).then((request) => request(this.axios, this.basePath));
    }

}
