// tslint:disable
/**
 * 健康助手后台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { FormResult } from '../models';
// @ts-ignore
import { NutritionRecordVo } from '../models';
// @ts-ignore
import { Result } from '../models';
/**
 * NutritionRecordControllerApi - axios parameter creator
 * @export
 */
export const NutritionRecordControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 根据id批量删除自定义营养计划表
         * @summary 根据id批量删除自定义营养计划表
         * @param {Array<string>} nutritionRecordVoIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionRecordDelete: async (nutritionRecordVoIds: Array<string>, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'nutritionRecordVoIds' is not null or undefined
            if (nutritionRecordVoIds === null || nutritionRecordVoIds === undefined) {
                throw new RequiredError('nutritionRecordVoIds','Required parameter nutritionRecordVoIds was null or undefined when calling nutritionRecordDelete.');
            }
            const localVarPath = `/nutritionRecord/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (nutritionRecordVoIds) {
                localVarQueryParameter['nutritionRecordVoIds'] = nutritionRecordVoIds;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 分页查询所有营养记录
         * @summary 分页查询所有营养记录
         * @param {number} page 
         * @param {number} num 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionRecordGet: async (page: number, num: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            if (page === null || page === undefined) {
                throw new RequiredError('page','Required parameter page was null or undefined when calling nutritionRecordGet.');
            }
            // verify required parameter 'num' is not null or undefined
            if (num === null || num === undefined) {
                throw new RequiredError('num','Required parameter num was null or undefined when calling nutritionRecordGet.');
            }
            const localVarPath = `/nutritionRecord/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (num !== undefined) {
                localVarQueryParameter['num'] = num;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 根据用户名称模糊分页查询所有营养记录表
         * @summary 根据用户名称模糊分页查询所有营养记录表
         * @param {string} page 
         * @param {string} num 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionRecordPageNumGet: async (page: string, num: string, name: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            if (page === null || page === undefined) {
                throw new RequiredError('page','Required parameter page was null or undefined when calling nutritionRecordPageNumGet.');
            }
            // verify required parameter 'num' is not null or undefined
            if (num === null || num === undefined) {
                throw new RequiredError('num','Required parameter num was null or undefined when calling nutritionRecordPageNumGet.');
            }
            // verify required parameter 'name' is not null or undefined
            if (name === null || name === undefined) {
                throw new RequiredError('name','Required parameter name was null or undefined when calling nutritionRecordPageNumGet.');
            }
            const localVarPath = `/nutritionRecord/{page}/{num}`
                .replace(`{${"page"}}`, encodeURIComponent(String(page)))
                .replace(`{${"num"}}`, encodeURIComponent(String(num)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 增加营养记录表(id需要为null)
         * @summary 增加营养记录表(id需要为null)
         * @param {NutritionRecordVo} [nutritionRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionRecordPost: async (nutritionRecordVo?: NutritionRecordVo, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/nutritionRecord/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof nutritionRecordVo !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(nutritionRecordVo !== undefined ? nutritionRecordVo : {}) : (nutritionRecordVo || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 修改自定义营养计划表
         * @summary 修改自定义营养计划表
         * @param {NutritionRecordVo} [nutritionRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionRecordPut: async (nutritionRecordVo?: NutritionRecordVo, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/nutritionRecord/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof nutritionRecordVo !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(nutritionRecordVo !== undefined ? nutritionRecordVo : {}) : (nutritionRecordVo || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NutritionRecordControllerApi - functional programming interface
 * @export
 */
export const NutritionRecordControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 根据id批量删除自定义营养计划表
         * @summary 根据id批量删除自定义营养计划表
         * @param {Array<string>} nutritionRecordVoIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async nutritionRecordDelete(nutritionRecordVoIds: Array<string>, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Result>> {
            const localVarAxiosArgs = await NutritionRecordControllerApiAxiosParamCreator(configuration).nutritionRecordDelete(nutritionRecordVoIds, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 分页查询所有营养记录
         * @summary 分页查询所有营养记录
         * @param {number} page 
         * @param {number} num 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async nutritionRecordGet(page: number, num: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormResult>> {
            const localVarAxiosArgs = await NutritionRecordControllerApiAxiosParamCreator(configuration).nutritionRecordGet(page, num, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 根据用户名称模糊分页查询所有营养记录表
         * @summary 根据用户名称模糊分页查询所有营养记录表
         * @param {string} page 
         * @param {string} num 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async nutritionRecordPageNumGet(page: string, num: string, name: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormResult>> {
            const localVarAxiosArgs = await NutritionRecordControllerApiAxiosParamCreator(configuration).nutritionRecordPageNumGet(page, num, name, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 增加营养记录表(id需要为null)
         * @summary 增加营养记录表(id需要为null)
         * @param {NutritionRecordVo} [nutritionRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async nutritionRecordPost(nutritionRecordVo?: NutritionRecordVo, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Result>> {
            const localVarAxiosArgs = await NutritionRecordControllerApiAxiosParamCreator(configuration).nutritionRecordPost(nutritionRecordVo, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 修改自定义营养计划表
         * @summary 修改自定义营养计划表
         * @param {NutritionRecordVo} [nutritionRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async nutritionRecordPut(nutritionRecordVo?: NutritionRecordVo, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Result>> {
            const localVarAxiosArgs = await NutritionRecordControllerApiAxiosParamCreator(configuration).nutritionRecordPut(nutritionRecordVo, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * NutritionRecordControllerApi - factory interface
 * @export
 */
export const NutritionRecordControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 根据id批量删除自定义营养计划表
         * @summary 根据id批量删除自定义营养计划表
         * @param {Array<string>} nutritionRecordVoIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionRecordDelete(nutritionRecordVoIds: Array<string>, options?: any): AxiosPromise<Result> {
            return NutritionRecordControllerApiFp(configuration).nutritionRecordDelete(nutritionRecordVoIds, options).then((request) => request(axios, basePath));
        },
        /**
         * 分页查询所有营养记录
         * @summary 分页查询所有营养记录
         * @param {number} page 
         * @param {number} num 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionRecordGet(page: number, num: number, options?: any): AxiosPromise<FormResult> {
            return NutritionRecordControllerApiFp(configuration).nutritionRecordGet(page, num, options).then((request) => request(axios, basePath));
        },
        /**
         * 根据用户名称模糊分页查询所有营养记录表
         * @summary 根据用户名称模糊分页查询所有营养记录表
         * @param {string} page 
         * @param {string} num 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionRecordPageNumGet(page: string, num: string, name: string, options?: any): AxiosPromise<FormResult> {
            return NutritionRecordControllerApiFp(configuration).nutritionRecordPageNumGet(page, num, name, options).then((request) => request(axios, basePath));
        },
        /**
         * 增加营养记录表(id需要为null)
         * @summary 增加营养记录表(id需要为null)
         * @param {NutritionRecordVo} [nutritionRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionRecordPost(nutritionRecordVo?: NutritionRecordVo, options?: any): AxiosPromise<Result> {
            return NutritionRecordControllerApiFp(configuration).nutritionRecordPost(nutritionRecordVo, options).then((request) => request(axios, basePath));
        },
        /**
         * 修改自定义营养计划表
         * @summary 修改自定义营养计划表
         * @param {NutritionRecordVo} [nutritionRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        nutritionRecordPut(nutritionRecordVo?: NutritionRecordVo, options?: any): AxiosPromise<Result> {
            return NutritionRecordControllerApiFp(configuration).nutritionRecordPut(nutritionRecordVo, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NutritionRecordControllerApi - object-oriented interface
 * @export
 * @class NutritionRecordControllerApi
 * @extends {BaseAPI}
 */
export class NutritionRecordControllerApi extends BaseAPI {
    /**
     * 根据id批量删除自定义营养计划表
     * @summary 根据id批量删除自定义营养计划表
     * @param {Array<string>} nutritionRecordVoIds 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NutritionRecordControllerApi
     */
    public nutritionRecordDelete(nutritionRecordVoIds: Array<string>, options?: any) {
        return NutritionRecordControllerApiFp(this.configuration).nutritionRecordDelete(nutritionRecordVoIds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 分页查询所有营养记录
     * @summary 分页查询所有营养记录
     * @param {number} page 
     * @param {number} num 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NutritionRecordControllerApi
     */
    public nutritionRecordGet(page: number, num: number, options?: any) {
        return NutritionRecordControllerApiFp(this.configuration).nutritionRecordGet(page, num, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 根据用户名称模糊分页查询所有营养记录表
     * @summary 根据用户名称模糊分页查询所有营养记录表
     * @param {string} page 
     * @param {string} num 
     * @param {string} name 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NutritionRecordControllerApi
     */
    public nutritionRecordPageNumGet(page: string, num: string, name: string, options?: any) {
        return NutritionRecordControllerApiFp(this.configuration).nutritionRecordPageNumGet(page, num, name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 增加营养记录表(id需要为null)
     * @summary 增加营养记录表(id需要为null)
     * @param {NutritionRecordVo} [nutritionRecordVo] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NutritionRecordControllerApi
     */
    public nutritionRecordPost(nutritionRecordVo?: NutritionRecordVo, options?: any) {
        return NutritionRecordControllerApiFp(this.configuration).nutritionRecordPost(nutritionRecordVo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 修改自定义营养计划表
     * @summary 修改自定义营养计划表
     * @param {NutritionRecordVo} [nutritionRecordVo] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NutritionRecordControllerApi
     */
    public nutritionRecordPut(nutritionRecordVo?: NutritionRecordVo, options?: any) {
        return NutritionRecordControllerApiFp(this.configuration).nutritionRecordPut(nutritionRecordVo, options).then((request) => request(this.axios, this.basePath));
    }

}
