// tslint:disable
/**
 * 健康助手后台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { FormResult } from '../models';
// @ts-ignore
import { Result } from '../models';
// @ts-ignore
import { WeightRecordVo } from '../models';
/**
 * WeightRecordControllerApi - axios parameter creator
 * @export
 */
export const WeightRecordControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 根据id批量删除自定义体重计划表
         * @summary 根据id批量删除自定义体重计划表
         * @param {Array<string>} weightRecordVoIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        weightRecordDelete: async (weightRecordVoIds: Array<string>, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'weightRecordVoIds' is not null or undefined
            if (weightRecordVoIds === null || weightRecordVoIds === undefined) {
                throw new RequiredError('weightRecordVoIds','Required parameter weightRecordVoIds was null or undefined when calling weightRecordDelete.');
            }
            const localVarPath = `/weightRecord/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (weightRecordVoIds) {
                localVarQueryParameter['weightRecordVoIds'] = weightRecordVoIds;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 分页查询所有体重记录
         * @summary 分页查询所有体重记录
         * @param {number} page 
         * @param {number} num 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        weightRecordGet: async (page: number, num: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            if (page === null || page === undefined) {
                throw new RequiredError('page','Required parameter page was null or undefined when calling weightRecordGet.');
            }
            // verify required parameter 'num' is not null or undefined
            if (num === null || num === undefined) {
                throw new RequiredError('num','Required parameter num was null or undefined when calling weightRecordGet.');
            }
            const localVarPath = `/weightRecord/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (num !== undefined) {
                localVarQueryParameter['num'] = num;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 根据用户名称模糊分页查询所有体重记录表
         * @summary 根据用户名称模糊分页查询所有体重记录表
         * @param {string} page 
         * @param {string} num 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        weightRecordPageNumGet: async (page: string, num: string, name: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'page' is not null or undefined
            if (page === null || page === undefined) {
                throw new RequiredError('page','Required parameter page was null or undefined when calling weightRecordPageNumGet.');
            }
            // verify required parameter 'num' is not null or undefined
            if (num === null || num === undefined) {
                throw new RequiredError('num','Required parameter num was null or undefined when calling weightRecordPageNumGet.');
            }
            // verify required parameter 'name' is not null or undefined
            if (name === null || name === undefined) {
                throw new RequiredError('name','Required parameter name was null or undefined when calling weightRecordPageNumGet.');
            }
            const localVarPath = `/weightRecord/{page}/{num}`
                .replace(`{${"page"}}`, encodeURIComponent(String(page)))
                .replace(`{${"num"}}`, encodeURIComponent(String(num)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 增加体重记录表(id需要为null)
         * @summary 增加体重记录表(id需要为null)
         * @param {WeightRecordVo} [weightRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        weightRecordPost: async (weightRecordVo?: WeightRecordVo, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/weightRecord/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof weightRecordVo !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(weightRecordVo !== undefined ? weightRecordVo : {}) : (weightRecordVo || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 修改自定义体重计划表
         * @summary 修改自定义体重计划表
         * @param {WeightRecordVo} [weightRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        weightRecordPut: async (weightRecordVo?: WeightRecordVo, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/weightRecord/`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof weightRecordVo !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(weightRecordVo !== undefined ? weightRecordVo : {}) : (weightRecordVo || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WeightRecordControllerApi - functional programming interface
 * @export
 */
export const WeightRecordControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 根据id批量删除自定义体重计划表
         * @summary 根据id批量删除自定义体重计划表
         * @param {Array<string>} weightRecordVoIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async weightRecordDelete(weightRecordVoIds: Array<string>, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Result>> {
            const localVarAxiosArgs = await WeightRecordControllerApiAxiosParamCreator(configuration).weightRecordDelete(weightRecordVoIds, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 分页查询所有体重记录
         * @summary 分页查询所有体重记录
         * @param {number} page 
         * @param {number} num 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async weightRecordGet(page: number, num: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormResult>> {
            const localVarAxiosArgs = await WeightRecordControllerApiAxiosParamCreator(configuration).weightRecordGet(page, num, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 根据用户名称模糊分页查询所有体重记录表
         * @summary 根据用户名称模糊分页查询所有体重记录表
         * @param {string} page 
         * @param {string} num 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async weightRecordPageNumGet(page: string, num: string, name: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FormResult>> {
            const localVarAxiosArgs = await WeightRecordControllerApiAxiosParamCreator(configuration).weightRecordPageNumGet(page, num, name, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 增加体重记录表(id需要为null)
         * @summary 增加体重记录表(id需要为null)
         * @param {WeightRecordVo} [weightRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async weightRecordPost(weightRecordVo?: WeightRecordVo, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Result>> {
            const localVarAxiosArgs = await WeightRecordControllerApiAxiosParamCreator(configuration).weightRecordPost(weightRecordVo, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 修改自定义体重计划表
         * @summary 修改自定义体重计划表
         * @param {WeightRecordVo} [weightRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async weightRecordPut(weightRecordVo?: WeightRecordVo, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Result>> {
            const localVarAxiosArgs = await WeightRecordControllerApiAxiosParamCreator(configuration).weightRecordPut(weightRecordVo, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * WeightRecordControllerApi - factory interface
 * @export
 */
export const WeightRecordControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 根据id批量删除自定义体重计划表
         * @summary 根据id批量删除自定义体重计划表
         * @param {Array<string>} weightRecordVoIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        weightRecordDelete(weightRecordVoIds: Array<string>, options?: any): AxiosPromise<Result> {
            return WeightRecordControllerApiFp(configuration).weightRecordDelete(weightRecordVoIds, options).then((request) => request(axios, basePath));
        },
        /**
         * 分页查询所有体重记录
         * @summary 分页查询所有体重记录
         * @param {number} page 
         * @param {number} num 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        weightRecordGet(page: number, num: number, options?: any): AxiosPromise<FormResult> {
            return WeightRecordControllerApiFp(configuration).weightRecordGet(page, num, options).then((request) => request(axios, basePath));
        },
        /**
         * 根据用户名称模糊分页查询所有体重记录表
         * @summary 根据用户名称模糊分页查询所有体重记录表
         * @param {string} page 
         * @param {string} num 
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        weightRecordPageNumGet(page: string, num: string, name: string, options?: any): AxiosPromise<FormResult> {
            return WeightRecordControllerApiFp(configuration).weightRecordPageNumGet(page, num, name, options).then((request) => request(axios, basePath));
        },
        /**
         * 增加体重记录表(id需要为null)
         * @summary 增加体重记录表(id需要为null)
         * @param {WeightRecordVo} [weightRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        weightRecordPost(weightRecordVo?: WeightRecordVo, options?: any): AxiosPromise<Result> {
            return WeightRecordControllerApiFp(configuration).weightRecordPost(weightRecordVo, options).then((request) => request(axios, basePath));
        },
        /**
         * 修改自定义体重计划表
         * @summary 修改自定义体重计划表
         * @param {WeightRecordVo} [weightRecordVo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        weightRecordPut(weightRecordVo?: WeightRecordVo, options?: any): AxiosPromise<Result> {
            return WeightRecordControllerApiFp(configuration).weightRecordPut(weightRecordVo, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WeightRecordControllerApi - object-oriented interface
 * @export
 * @class WeightRecordControllerApi
 * @extends {BaseAPI}
 */
export class WeightRecordControllerApi extends BaseAPI {
    /**
     * 根据id批量删除自定义体重计划表
     * @summary 根据id批量删除自定义体重计划表
     * @param {Array<string>} weightRecordVoIds 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightRecordControllerApi
     */
    public weightRecordDelete(weightRecordVoIds: Array<string>, options?: any) {
        return WeightRecordControllerApiFp(this.configuration).weightRecordDelete(weightRecordVoIds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 分页查询所有体重记录
     * @summary 分页查询所有体重记录
     * @param {number} page 
     * @param {number} num 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightRecordControllerApi
     */
    public weightRecordGet(page: number, num: number, options?: any) {
        return WeightRecordControllerApiFp(this.configuration).weightRecordGet(page, num, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 根据用户名称模糊分页查询所有体重记录表
     * @summary 根据用户名称模糊分页查询所有体重记录表
     * @param {string} page 
     * @param {string} num 
     * @param {string} name 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightRecordControllerApi
     */
    public weightRecordPageNumGet(page: string, num: string, name: string, options?: any) {
        return WeightRecordControllerApiFp(this.configuration).weightRecordPageNumGet(page, num, name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 增加体重记录表(id需要为null)
     * @summary 增加体重记录表(id需要为null)
     * @param {WeightRecordVo} [weightRecordVo] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightRecordControllerApi
     */
    public weightRecordPost(weightRecordVo?: WeightRecordVo, options?: any) {
        return WeightRecordControllerApiFp(this.configuration).weightRecordPost(weightRecordVo, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 修改自定义体重计划表
     * @summary 修改自定义体重计划表
     * @param {WeightRecordVo} [weightRecordVo] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeightRecordControllerApi
     */
    public weightRecordPut(weightRecordVo?: WeightRecordVo, options?: any) {
        return WeightRecordControllerApiFp(this.configuration).weightRecordPut(weightRecordVo, options).then((request) => request(this.axios, this.basePath));
    }

}
