// tslint:disable
/**
 * 健康助手后台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DiseaseRecordVo
 */
export interface DiseaseRecordVo {
    /**
     * 
     * @type {number}
     * @memberof DiseaseRecordVo
     */
    id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiseaseRecordVo
     */
    userId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiseaseRecordVo
     */
    hypertension?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiseaseRecordVo
     */
    hyperlipemia?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiseaseRecordVo
     */
    hyperglycemia?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DiseaseRecordVo
     */
    hypercholesterol?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DiseaseRecordVo
     */
    username?: string | null;
}


