// tslint:disable
/**
 * 健康助手后台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FoodRecordVo
 */
export interface FoodRecordVo {
    /**
     * 
     * @type {number}
     * @memberof FoodRecordVo
     */
    id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FoodRecordVo
     */
    userId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FoodRecordVo
     */
    foodId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof FoodRecordVo
     */
    foodWeight?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FoodRecordVo
     */
    foodType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FoodRecordVo
     */
    recordTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FoodRecordVo
     */
    username?: string | null;
}


