// tslint:disable
/**
 * 健康助手后台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FoodMapping
 */
export interface FoodMapping {
    /**
     * 
     * @type {number}
     * @memberof FoodMapping
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FoodMapping
     */
    foodName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FoodMapping
     */
    nutritionId?: number | null;
}


