// tslint:disable
/**
 * 健康助手后台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Nutrition
 */
export interface Nutrition {
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Nutrition
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    reliang?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    danbai?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    zhifang?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    tanshui?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    xianwei?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    va?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    huluobosu?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    yansuan?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    vc?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    ve?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    danguchun?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    jia?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    na?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    gai?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    mei?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    tie?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    meng?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    xin?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    tong?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    lin?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Nutrition
     */
    xi?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Nutrition
     */
    pic?: string | null;
}


