// tslint:disable
/**
 * 健康助手后台
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    age?: number | null;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    gender?: number | null;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    height?: number | null;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    weight?: number | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    tel?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string | null;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    targetWeight?: number | null;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    bmi?: number | null;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    isVip?: number | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    geography?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    head?: string | null;
}


